package com.qcadoo.plugin.internal.api;

public enum PluginOperationStatus {
    DEPENDENCIES_TO_ENABLE, SUCCESS, SUCCESS_WITH_RESTART, UNSATISFIED_DEPENDENCIES, DEPENDENCIES_TO_DISABLE, SYSTEM_PLUGIN_DISABLING, SUCCESS_WITH_MISSING_DEPENDENCIES, CORRUPTED_PLUGIN, CANNOT_UPLOAD_PLUGIN, CANNOT_INSTALL_PLUGIN_FILE, SYSTEM_PLUGIN_UNINSTALLING, SYSTEM_PLUGIN_UPDATING, CANNOT_DOWNGRADE_PLUGIN, DEPENDENCIES_TO_UNINSTALL, UNSATISFIED_DEPENDENCIES_AFTER_UPDATE;
}
