package com.qcadoo.plugin;

public enum PluginOperationStatus {
    DISABLED_DEPENDENCIES, SUCCESS, SUCCESS_WITH_RESTART, UNSATISFIED_DEPENDENCIES, ENABLED_DEPENDENCIES, SYSTEM_PLUGIN_DISABLING, SUCCESS_WITH_MISSING_DEPENDENCIES, CORRUPTED_PLUGIN, CANNOT_UPLOAD_PLUGIN, CANNOT_INSTALL_PLUGIN, CANNOT_UNINSTALL_PLUGIN, SYSTEM_PLUGIN_UNINSTALLING, SYSTEM_PLUGIN_UPDATING;
}
